server:
  port: 9999

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.178.205:3306/mms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis: # redis设置
    host: 110.40.178.205 # IP
    port: 6379      # 端口
    password: zhang232531       # 密码
    connect-timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-wait: 200s
        max-idle: 8
        min-idle: 0


  #  设置日志
logging:
  level:
    root: warn
    com.moumouzhandui.mms: info
  file:
    name: log/mms-production.log

# 上传模式
upload:
  mode: local
  local:
    # nginx映射本地文件路径，无域名则为 ip:82
    url: http://110.40.178.205:82/
    # 本地文件存储路径
    path: /usr/local/upload/

files:
  upload:
    path:
      images: /home/ubuntu/my_project/mms/mms-springboot/files/images/
  url:
    base: "http://110.40.178.205:9999/file/image/download/"