spring:
  profiles:
    active: production
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    path match:
      # 配置策略
      matching-strategy: ant_path_matcher
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: 1738252674@qq.com
    password: hjfumurykpbvfacb
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*.xml  # 扫描所有mybatis的配置文件






