spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379



  #  设置日志
logging:
  level:
    root: info
    com.moumouzhandui.mms: debug
  file:
    name: mms-springboot/log/mms-develop.log